# Generated by Django 5.2.7 on 2025-11-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
