# Generated by Django 5.2.7 on 2025-11-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_publication_summary_alter_galleryitem_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryitem',
            old_name='title',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='caption',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery/%Y/%m/'),
        ),
    ]
