# Generated by Django 5.2.7 on 2025-11-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_rename_title_galleryitem_event_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='event_name',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='resources.galleryevent'),
        ),
    ]
