# Generated by Django 5.2.7 on 2025-11-09 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_galleryevent_alter_galleryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='caption',
        ),
        migrations.AlterField(
            model_name='galleryevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='resources.galleryevent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
