# Generated by Django 5.2.7 on 2025-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_galleryevent_options_alter_galleryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/previews/'),
        ),
    ]
