# Generated by Django 5.2.7 on 2025-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_publication_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryevent',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
